version: "3.7"
services:
  app:
    build:
      args:
        user: nomads
        uid: 1001
      context: ./
      dockerfile: Dockerfile
    image: nomads    
    container_name: nomads-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - nomads

  db:
    image: mysql:8.0
    container_name: nomads-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - nomads

  nginx:
    image: nginx:alpine
    container_name: nomads-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - nomads

networks:
  nomads:
    driver: bridge