name: Main CI Workflow

permissions:
  security-events: write
  pull-requests: read
  contents: write
  id-token: write
  statuses: write
  actions: read
  pages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  unit-test:
    uses: ./.github/workflows/ci-test.yml
  
  sca-test:
    needs: unit-test
    uses: ./.github/workflows/ci-soos-sca.yml
    secrets:
      client_id: ${{ secrets.SOOS_CLIENT_ID }}
      api_key: ${{ secrets.SOOS_API_KEY }}

  sast-test:
    needs: sca-test
    uses: ./.github/workflows/ci-sonarcloud-sast.yml
    secrets:
      GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }} 
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-image-trivy:
    needs: sast-test
    uses: ./.github/workflows/ci-build-deploy.yml
    with:
      # docker_image: 'docker.io/airist/nomadd:${{ github.sha }}'
      docker_image: 'docker.io/airist/nomadd'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 