name: Main CI Workflow

permissions:
  security-events: write
  pull-requests: read
  contents: write
  id-token: write
  statuses: write
  actions: read
  pages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types:
      - published

jobs:

  unit-test:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/ci-test.yml

  sca-test:
    if: github.ref == 'refs/heads/main'
    needs: unit-test
    uses: ./.github/workflows/ci-soos-sca.yml
    secrets:
      client_id: ${{ secrets.SOOS_CLIENT_ID }}
      api_key: ${{ secrets.SOOS_API_KEY }}

  sast-test:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: sca-test
    uses: ./.github/workflows/ci-sonarcloud-sast.yml
    secrets:
      GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }} 
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-image-staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: sast-test
    uses: ./.github/workflows/ci-build-deploy.yml
    with:
      docker_image: 'docker.io/airist/nomadd-dev'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  sast-test-release:
    if: github.event_name == 'release'
    uses: ./.github/workflows/ci-sonarcloud-sast.yml
    secrets:
      GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }} 
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-image-production:
    if: github.event_name == 'release'
    uses: ./.github/workflows/ci-build-deploy.yml
    with:
      docker_image: 'docker.io/airist/nomadd-release-${{ github.event.release.tag_name }}'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
